### ISSUE TITLE
运行main.py报错

### ISSUE THREAD

**Issue by AlphaRunTime** [csgo-adc/TencentClassDownloader#2]
D:\py\TencentClassDownloader>python main.py
Traceback (most recent call last):
  File "D:\py\TencentClassDownloader\main.py", line 107, in <module>
    pp.creat_download_info()
  File "D:\py\TencentClassDownloader\main.py", line 48, in creat_download_info
    chapter_list = t.get_course_list()
                   ^^^^^^^^^^^^^^^^^^^
  File "D:\py\TencentClassDownloader\tencent_request.py", line 46, in get_course_list
    chapters_list = tlist['result']['terms'][0]['chapter_info']
                    ~~~~~^^^^^^^^^^
KeyError: 'result'

**Comment by AlphaRunTime** [comment]
哈喽 , 能给看看这个问题吗

**Comment by csgo-adc** [comment]
这个看着应该是解析数据时候有问题，具体得看看给你返回时的数据是什么样的。
通常来说这种情况先检查一下你写的URL格式对不对，QQ号有没有填，等等吧

**Comment by PooSheng** [comment]
问题解决了吗？我的也是这样
