### ISSUE TITLE
使用自己的cookie后总是提示Invalid header value

### ISSUE THREAD

**Issue by LoserLus** [csgo-adc/TencentClassDownloader#5]
从浏览器中导出的cookie：
```javascript
Hm_lpvt_0c196c536f609d373a16d246a117fd44=1723548661;_qimei_fingerprint=77 dec3689c55584a5fe814960e113756;tdw_data_flowid=;_qimei_uuid42=1850315222 a10074c1a0e132a413e89c6c436b5642;LW_sid=81 Z7s1a6N810T9s6j771r5k0X9;auth_version=2.0;RK=iBMEMVBJO7;HMACCOUNT=3E30 FF5F80000713;_pathcode=0.7989451489815687;uin=144115380269272630;sessionPath=17239689940265972099557;tdw_first_visited=1;pgv_pvid=1967995835551010;p_uin=144115380200272630;tdw_data={"ver4":"4","ver5":"","ver6":"","refer":"","from_channel":"","path":"B-0.7989451481115687","auin":"-","uin":"144115380269272630","real_uin":"44115383369272630"};Hm_lvt_0c196c536f609d373a16d246a117fd44=1723774999,17237708207,1723795194,1721266807;pgv_info=ssid=s3571112750;ke_login_type=1;_qimei_h38=e06d60c2c1a0e132a413e89c0200000c718503;_qimei_q36=;eas_sid=K147q0q001U249B296S0y2b1w3;iip=0;LW_uid=c1e7v1u618a0a9q1C4D9Z8e577;p_luin=144115380269272630;pac_uid=0_1 f43a62141337;ptcz=7 d42a630f3f67c39db1e720f2f0da10622fd08011aa58b3ffeb7629be17764da;qq_domain_video_guid_verify=d05ddb39ed8b953c;tdw_auin_data=-;tdw_data_new_2={"auin":"-","sourcetype":"","sourcefrom":"","ver9":"144115380269272630","uin":"144115380269272630","visitor_id":"5699652069159569","ver10":"","url_page":"personalcenter_classschedule","url_module":"","url_position":"","sessionPath":"17239686400265972099557"};tdw_data_testid=;ts_last=ke.qq.com/webcourse/5785339/106236256;ts_uid=8133403520;uid_a2=56907 bcc4678ae11e74bab3831abe8b12be6083f663bc245ff20e71e883ec04305489b77deca89197fdcb58b4c75d046bf970d6e0343342f1a00ff7b7b593a40f5ad56212b01c482;uid_appid=1401990008;uid_origin_auth_type=2;uid_origin_uid_type=2;uid_type=1612;uid_uin=144115380269213630
```
格式化后：
```javascript
Hm_lpvt_0c196c536f609d373a16d246a117fd44 = 1723548661;
_qimei_fingerprint = 77 dec3689c55584a5fe814960e113756;
tdw_data_flowid = ;
_qimei_uuid42 = 1850315222 a10074c1a0e132a413e89c6c436b5642;
LW_sid = 81 Z7s1a6N810T9s6j771r5k0X9;
auth_version = 2.0;
RK = iBMEMVBJO7;
HMACCOUNT = 3E30 FF5F80000713;
_pathcode = 0.7989451489815687;
uin = 144115380269272630;
sessionPath = 17239689940265972099557;
tdw_first_visited = 1;
pgv_pvid = 1967995835551010;
p_uin = 144115380200272630;
tdw_data = {
	"ver4": "4",
	"ver5": "",
	"ver6": "",
	"refer": "",
	"from_channel": "",
	"path": "B-0.7989451481115687",
	"auin": "-",
	"uin": "144115380269272630",
	"real_uin": "44115383369272630"
};
Hm_lvt_0c196c536f609d373a16d246a117fd44 = 1723774999, 17237708207, 1723795194, 1721266807;
pgv_info = ssid = s3571112750;
ke_login_type = 1;
_qimei_h38 = e06d60c2c1a0e132a413e89c0200000c718503;
_qimei_q36 = ;
eas_sid = K147q0q001U249B296S0y2b1w3;
iip = 0;
LW_uid = c1e7v1u618a0a9q1C4D9Z8e577;
p_luin = 144115380269272630;
pac_uid = 0_1 f43a62141337;
ptcz = 7 d42a630f3f67c39db1e720f2f0da10622fd08011aa58b3ffeb7629be17764da;
qq_domain_video_guid_verify = d05ddb39ed8b953c;
tdw_auin_data = -;
tdw_data_new_2 = {
	"auin": "-",
	"sourcetype": "",
	"sourcefrom": "",
	"ver9": "144115380269272630",
	"uin": "144115380269272630",
	"visitor_id": "5699652069159569",
	"ver10": "",
	"url_page": "personalcenter_classschedule",
	"url_module": "",
	"url_position": "",
	"sessionPath": "17239686400265972099557"
};
tdw_data_testid = ;
ts_last = ke.qq.com / webcourse / 5785339 / 106236256;
ts_uid = 8133403520;
uid_a2 = 56907 bcc4678ae11e74bab3831abe8b12be6083f663bc245ff20e71e883ec04305489b77deca89197fdcb58b4c75d046bf970d6e0343342f1a00ff7b7b593a40f5ad56212b01c482;
uid_appid = 1401990008;
uid_origin_auth_type = 2;
uid_origin_uid_type = 2;
uid_type = 1612;
uid_uin = 144115380269213630
```
配置文件（我使用的微信登录，没有绑定QQ号）：
```yaml
[QQ]
number = 123456789

[url]
url = https://ke.qq.com/webcourse/5855339/106260256

[process]
process_num = 8

[output]
save_path = ./download

[clarity]
clarity = 1
# 1 = high
# 2 = mid
# 3 = low
```
给出的报错信息：
```python
Traceback (most recent call last):
  File "main.py", line 107, in <module>
    pp.creat_download_info()
  File "main.py", line 48, in creat_download_info
    chapter_list = t.get_course_list()
  File "/home/lyl/TencentClassDownloader/tencent_request.py", line 44, in get_course_list
    content = requests.get(terms_url, headers=self.header).text
  File "/home/lyl/miniconda3/envs/tcd/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/lyl/miniconda3/envs/tcd/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/lyl/miniconda3/envs/tcd/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lyl/miniconda3/envs/tcd/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/lyl/miniconda3/envs/tcd/lib/python3.8/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/lyl/miniconda3/envs/tcd/lib/python3.8/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/home/lyl/miniconda3/envs/tcd/lib/python3.8/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/home/lyl/miniconda3/envs/tcd/lib/python3.8/site-packages/urllib3/connection.py", line 397, in request
    self.putheader(header, value)
  File "/home/lyl/miniconda3/envs/tcd/lib/python3.8/site-packages/urllib3/connection.py", line 311, in putheader
    super().putheader(header, *values)
  File "/home/lyl/miniconda3/envs/tcd/lib/python3.8/http/client.py", line 1234, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b'Hm_lpvt_0c196c536f609d373a16d246a117fd44=1723968661;_qimei_fingerprint=77dec3689c55584a5fe814960e113756;tdw_data_flowid=;_qimei_uuid42=1850315222a10074c1a0e132a413e89c6c436b5642;LW_sid=81Z7s1a6N810T9s6j771r5k0X9;auth_version=2.0;RK=iBMEMVBJO7;HMACCOUNT=3E30FF5F80000713;_pathcode=0.7989451489815687;uin=144115380269272630;sessionPath=17239686440265972099557;tdw_first_visited=1;pgv_pvid=1967995850351010;p_uin=144115380269272630;tdw_data={"ver4":"4","ver5":"","ver6":"","refer":"","from_channel":"","path":"B-0.7989451489815687","auin":"-","uin":"144115380269272630","real_uin":"44115380269272630"};Hm_lvt_0c196c536f609d373a16d246a117fd44=1723774985,1723778207,1723795194,1723966807;pgv_info=ssid=s3571112750;ke_login_type=1;_qimei_h38=e06d60c2c1a0e132a413e89c0200000c718503;_qimei_q36=;eas_sid=K147q0q001U249B2p4S0y2b1w3;iip=0;LW_uid=c1e7v1u618a0a9q1C4D9Z8e577;p_luin=144115380269272630;pac_uid=0_1f43a62141337;ptcz=7d42a630f3f67c39db1e720f2f0da10622fd08011aa58b3ffeb7629be17764da;qq_domain_video_guid_verify=d05ddb39ed8b953c;tdw_auin_data=-;tdw_data_new_2={"auin":"-","sourcetype":"","sourcefrom":"","ver9":"144115380269272630","uin":"144115380269272630","visitor_id":"5699652069159569","ver10":"","url_page":"personalcenter_classschedule","url_module":"","url_position":"","sessionPath":"17239686440265972099557"};tdw_data_testid=;ts_last=ke.qq.com/webcourse/5855339/106260256;ts_uid=8176403520;uid_a2=56907bcc4678ae11e74bab3831abe8b05be6083f663bc245ff20e71e883ec04305489b77deca89197fdcb58b4c75d046bf970d6e0343342f1a00ff7b7b593a40f5ad56212b01c482;uid_appid=1400000008;uid_origin_auth_type=2;uid_origin_uid_type=2;uid_type=1012;uid_uin=144115380269272630\n'
```

**Comment by csgo-adc** [comment]
这里是我偷懒了，cookie加载时候没做容错处理，看你这应该是cookie报错了，因为你cookie的结尾有个换行符
你粘贴cookie的时候就直接把从浏览器拷贝出来的cookie原封不动的粘贴过去，不要做格式化，有换行就把额外的行删掉
